service: tunez
image: my-user/my-app
servers:
  web:
    - 195.15.213.134
proxy:
  ssl: false
  host: tunez.app
  app_port: 4000
registry:
  username: royalmist
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: amd64
env:
  clear:
    PHX_SERVER: true
    POOL_SIZE: "10"
    PHX_HOST: "tunez.app"
  secret:
    - DATABASE_URL
    - SECRET_KEY_BASE
    - TOKEN_SIGNING_SECRET
ssh:
  user: ubuntu