service: tunez
image: royalmist/tunez
context: .
ssh:
  user: ubuntu
servers:
  web:
    - 195.15.213.134
registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: amd64
proxy:
  ssl: true
  host: tunez.thibault.swiss
  app_port: 4000
env:
  clear:
    PHX_SERVER: true
    POOL_SIZE: "10"
    PHX_HOST: "tunez.app"
  secret:
    - DATABASE_URL
    - SECRET_KEY_BASE
    - TOKEN_SIGNING_SECRET
