service: tunez
image: my-user/my-app
servers:
  web:
    - 192.168.64.12
    - 192.168.64.13
proxy:
  ssl: false
  host: tunez.app
  app_port: 4000
registry:
  username: royalmist
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: arm64
env:
  clear:
    PHX_SERVER: true
    POOL_SIZE: "10"
    PHX_HOST: "tunez.app"
  secret:
    - DATABASE_URL
    - SECRET_KEY_BASE
    - TOKEN_SIGNING_SECRET
ssh:
  user: ubuntu
accessories:
  db:
    image: postgres:17
    host: 192.168.64.11
    port: 5432
    env:
      clear:
        POSTGRES_DB: "tunez"
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
