service: tunez
image: royalmist/tunez
ssh:
  user: ubuntu
servers:
  web:
    - 195.15.213.134
registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  context: .
  arch: amd64
proxy:
  ssl: true
  host: tunez.thibault.swiss
  app_port: 4000
  healthcheck:
    interval: 3
    path: /
    timeout: 10
volumes:
  - "brickstreet_storage:/rails/storage"
env:
  clear:
    PHX_SERVER: true
    POOL_SIZE: "10"
    PHX_HOST: "tunez.app"
  secret:
    - SECRET_KEY_BASE
    - TOKEN_SIGNING_SECRET
aliases:
  console: app exec --interactive --reuse "./bin/tunez remote"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
